"""
Post-build script – called by mox.bat / mox.sh after every project build.

Invocation (generated by libmox.lua mox_runpy_postbuild):
  mox postbuild <project_name> <project_path> <output_path>
                <project_configuration> <is_debug> <project_architecture> <project_kind>

Arguments
---------
project_name          Name of the project that was just built (e.g. "MyApp")
project_path          Absolute path to the project directory
output_path           Absolute path to the build output directory (bin/)
project_configuration Build configuration name (e.g. "Debug", "Release")
is_debug              "true" | "false"
project_architecture  Premake5 architecture string (e.g. "x86_64", "ARM64")
project_kind          Premake5 project kind (e.g. "ConsoleApp", "WindowedApp",
                      "SharedLib", "StaticLib")

Copyright (c) 2026 Moxibyte GmbH

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
"""

import os
import sys
import argparse
import subprocess

# Premake5 canonical kind names for executable projects
_EXECUTABLE_KINDS = {
    'ConsoleApp', 'WindowedApp',
    # Xcode product-type strings emitted by some Premake5 xcode4 backend versions
    'com.apple.product-type.tool',
    'com.apple.product-type.application',
}

if __name__ == '__main__':
    p = argparse.ArgumentParser(
        prog='postbuild.py',
        allow_abbrev=False,
        description='Post-build hook called automatically by libmox.lua after every project build.',
    )
    p.add_argument('--project_name',          required=True,  help='Name of the project (e.g. "MyApp")')
    p.add_argument('--project_path',          required=True,  help='Path to the project source directory')
    p.add_argument('--output_path',           required=True,  help='Path to the build output directory (bin/)')
    p.add_argument('--project_configuration', required=True,  help='Build configuration name (e.g. "Debug", "Release")')
    p.add_argument('--is_debug',              required=True,  help='"true" if this is a debug configuration, "false" otherwise')
    p.add_argument('--project_architecture',  required=True,  help='Premake5 architecture string (e.g. "x86_64", "ARM64")')
    p.add_argument('--project_kind',          required=True,  help='Premake5 project kind (e.g. "ConsoleApp", "WindowedApp", "SharedLib", "StaticLib")')
    args = p.parse_args()

    is_debug = args.is_debug.lower() == 'true'
    # Strip any trailing slashes so path joining works cleanly on all platforms
    output_path = args.output_path.rstrip('/\\')

    print(f"[postbuild] {args.project_name}: kind={args.project_kind!r} arch={args.project_architecture!r} conf={args.project_configuration!r} is_debug={is_debug}", flush=True)

    # -------------------------------------------------------------------------
    # DLL distribution – copy DLLs from ./dlls/<Conf>-<arch>/ into output_path.
    # Only meaningful for executable outputs; skip libraries.
    # -------------------------------------------------------------------------
    if args.project_kind in _EXECUTABLE_KINDS:
        conf_label = 'Debug' if is_debug else 'Release'
        dlls_src   = os.path.join('.', 'dlls', f'{conf_label}-{args.project_architecture}')

        if os.path.isdir(dlls_src):
            subprocess.run(
                [sys.executable, './scripts/dist_dlls.py', dlls_src, output_path],
                check=False,
            )

    # -------------------------------------------------------------------------
    # Add your own post-build logic below.
    # All project information is available via `args.*`.
    # -------------------------------------------------------------------------
