"""
Pre-build script – called by mox.bat / mox.sh before every project build.

Invocation (generated by libmox.lua mox_runpy_prebuild):
  mox prebuild <project_name> <project_path> <output_path>
               <project_configuration> <is_debug> <project_architecture> <project_kind>

Copyright (c) 2026 Moxibyte GmbH

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
"""

import argparse

if __name__ == '__main__':
    p = argparse.ArgumentParser(
        prog='prebuild.py',
        allow_abbrev=False,
        description='Pre-build hook called automatically by libmox.lua before every project build.',
    )
    p.add_argument('--project_name',          required=True,  help='Name of the project (e.g. "MyApp")')
    p.add_argument('--project_path',          required=True,  help='Path to the project source directory')
    p.add_argument('--output_path',           required=True,  help='Path to the build output directory (bin/)')
    p.add_argument('--project_configuration', required=True,  help='Build configuration name (e.g. "Debug", "Release")')
    p.add_argument('--is_debug',              required=True,  help='"true" if this is a debug configuration, "false" otherwise')
    p.add_argument('--project_architecture',  required=True,  help='Premake5 architecture string (e.g. "x86_64", "ARM64")')
    p.add_argument('--project_kind',          required=True,  help='Premake5 project kind (e.g. "ConsoleApp", "WindowedApp", "SharedLib", "StaticLib")')
    args = p.parse_args()

    is_debug = args.is_debug.lower() == 'true'

    # -------------------------------------------------------------------------
    # Add your own pre-build logic below.
    # All project information is available via `args.*`.
    # -------------------------------------------------------------------------
